version: '3.4'

services:
  employeebirthdaygiftvotingsystem:
    env_file:
        - .env
    image: ${DOCKER_REGISTRY-}employeebirthdaygiftvotingsystem
    depends_on: 
        - postgres
    build:
      context: .
      dockerfile: EmployeeBirthdayGiftVotingSystem/Dockerfile

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}
        PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - ./volumes/postgres:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./volumes/pgadmin4:/var/lib/pgadmin
    ports:
      - 5433:80
    depends_on:
      - postgres
